//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.27 at 08:20:59 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mohamedatta.com/xsds/school", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mohamedatta.school.schemas.students;
